package nukeeng.main.blocks.rtg.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelRTG_BetaM extends ModelBase
{
	 //fields
    ModelRenderer Frame1;
    ModelRenderer Frame2;
    ModelRenderer Frame3;
    ModelRenderer Frame4;
    ModelRenderer Frame5;
    ModelRenderer Frame6;
    ModelRenderer Frame8;
    ModelRenderer Frame9;
    ModelRenderer Frame10;
    ModelRenderer Frame11;
    ModelRenderer Frame12;
    ModelRenderer Frame13;
    ModelRenderer Frame14;
    ModelRenderer Frame15;
    ModelRenderer GPHS;
    ModelRenderer HeatSpreader;
    ModelRenderer TEGHolder;
    ModelRenderer Base;
    ModelRenderer HeatRing;
    ModelRenderer Fin1;
    ModelRenderer Fin2;
    ModelRenderer Fin3;
    ModelRenderer Fin4;
    ModelRenderer Fin5;
    ModelRenderer Fin6;
    ModelRenderer Fin7;
    ModelRenderer Fin9;
    ModelRenderer Fin8;
    ModelRenderer Fin10;
    ModelRenderer Fin11;
    ModelRenderer Fin12;
    ModelRenderer ControlBox;
    ModelRenderer Socket;
  
  public ModelRTG_BetaM()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Frame1 = new ModelRenderer(this, 0, 0);
      Frame1.addBox(0F, 0F, 0F, 16, 1, 1);
      Frame1.setRotationPoint(-8F, 9F, -8F);
      Frame1.setTextureSize(64, 32);
      Frame1.mirror = true;
      setRotation(Frame1, 0F, 0F, 0F);
      Frame2 = new ModelRenderer(this, 0, 0);
      Frame2.addBox(0F, 0F, 0F, 16, 1, 1);
      Frame2.setRotationPoint(-8F, 9F, 7F);
      Frame2.setTextureSize(64, 32);
      Frame2.mirror = true;
      setRotation(Frame2, 0F, 0F, 0F);
      Frame3 = new ModelRenderer(this, 0, 3);
      Frame3.addBox(0F, 0F, 0F, 1, 1, 14);
      Frame3.setRotationPoint(-8F, 9F, -7F);
      Frame3.setTextureSize(64, 32);
      Frame3.mirror = true;
      setRotation(Frame3, 0F, 0F, 0F);
      Frame4 = new ModelRenderer(this, 0, 3);
      Frame4.addBox(0F, 0F, 0F, 1, 1, 14);
      Frame4.setRotationPoint(-3F, 23F, -7F);
      Frame4.setTextureSize(64, 32);
      Frame4.mirror = true;
      setRotation(Frame4, 0F, 0F, 0F);
      Frame5 = new ModelRenderer(this, 0, 3);
      Frame5.addBox(0F, 0F, 0F, 1, 1, 14);
      Frame5.setRotationPoint(7F, 9F, -7F);
      Frame5.setTextureSize(64, 32);
      Frame5.mirror = true;
      setRotation(Frame5, 0F, 0F, 0F);
      Frame6 = new ModelRenderer(this, 0, 3);
      Frame6.addBox(0F, 0F, 0F, 1, 1, 14);
      Frame6.setRotationPoint(2F, 23F, -7F);
      Frame6.setTextureSize(64, 32);
      Frame6.mirror = true;
      setRotation(Frame6, 0F, 0F, 0F);
      Frame8 = new ModelRenderer(this, 31, 3);
      Frame8.addBox(0F, 0F, 0F, 1, 15, 1);
      Frame8.setRotationPoint(7F, 8F, -8F);
      Frame8.setTextureSize(64, 32);
      Frame8.mirror = true;
      setRotation(Frame8, 0F, 0F, 0F);
      Frame9 = new ModelRenderer(this, 31, 3);
      Frame9.addBox(0F, 0F, 0F, 1, 15, 1);
      Frame9.setRotationPoint(-8F, 8F, -8F);
      Frame9.setTextureSize(64, 32);
      Frame9.mirror = true;
      setRotation(Frame9, 0F, 0F, 0F);
      Frame10 = new ModelRenderer(this, 31, 3);
      Frame10.addBox(0F, 0F, 0F, 1, 15, 1);
      Frame10.setRotationPoint(-8F, 8F, 7F);
      Frame10.setTextureSize(64, 32);
      Frame10.mirror = true;
      setRotation(Frame10, 0F, 0F, 0F);
      Frame11 = new ModelRenderer(this, 31, 3);
      Frame11.addBox(0F, 0F, 0F, 1, 15, 1);
      Frame11.setRotationPoint(7F, 8F, 7F);
      Frame11.setTextureSize(64, 32);
      Frame11.mirror = true;
      setRotation(Frame11, 0F, 0F, 0F);
      Frame12 = new ModelRenderer(this, 0, 0);
      Frame12.addBox(0F, 0F, 0F, 16, 1, 1);
      Frame12.setRotationPoint(-8F, 23F, -8F);
      Frame12.setTextureSize(64, 32);
      Frame12.mirror = true;
      setRotation(Frame12, 0F, 0F, 0F);
      Frame13 = new ModelRenderer(this, 0, 3);
      Frame13.addBox(0F, 0F, 0F, 1, 1, 14);
      Frame13.setRotationPoint(-8F, 23F, -7F);
      Frame13.setTextureSize(64, 32);
      Frame13.mirror = true;
      setRotation(Frame13, 0F, 0F, 0F);
      Frame14 = new ModelRenderer(this, 0, 0);
      Frame14.addBox(0F, 0F, 0F, 16, 1, 1);
      Frame14.setRotationPoint(-8F, 23F, 7F);
      Frame14.setTextureSize(64, 32);
      Frame14.mirror = true;
      setRotation(Frame14, 0F, 0F, 0F);
      Frame15 = new ModelRenderer(this, 0, 3);
      Frame15.addBox(0F, 0F, 0F, 1, 1, 14);
      Frame15.setRotationPoint(7F, 23F, -7F);
      Frame15.setTextureSize(64, 32);
      Frame15.mirror = true;
      setRotation(Frame15, 0F, 0F, 0F);
      GPHS = new ModelRenderer(this, 36, 7);
      GPHS.addBox(0F, 0F, 0F, 4, 2, 4);
      GPHS.setRotationPoint(-2F, 20F, -2F);
      GPHS.setTextureSize(64, 32);
      GPHS.mirror = true;
      setRotation(GPHS, 0F, 0F, 0F);
      HeatSpreader = new ModelRenderer(this, 36, 15);
      HeatSpreader.addBox(0F, 0F, 0F, 5, 1, 5);
      HeatSpreader.setRotationPoint(-2.5F, 16.6F, -2.5F);
      HeatSpreader.setTextureSize(64, 32);
      HeatSpreader.mirror = true;
      setRotation(HeatSpreader, 0F, 0F, 0F);
      TEGHolder = new ModelRenderer(this, 55, 7);
      TEGHolder.addBox(0F, 0F, 0F, 2, 5, 2);
      TEGHolder.setRotationPoint(-1F, 15F, -1F);
      TEGHolder.setTextureSize(64, 32);
      TEGHolder.mirror = true;
      setRotation(TEGHolder, 0F, 0F, 0F);
      Base = new ModelRenderer(this, 36, 0);
      Base.addBox(0F, 0F, 0F, 5, 1, 5);
      Base.setRotationPoint(-2.5F, 22F, -2.5F);
      Base.setTextureSize(64, 32);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0F);
      HeatRing = new ModelRenderer(this, 36, 23);
      HeatRing.addBox(0F, 0F, 0F, 6, 1, 6);
      HeatRing.setRotationPoint(-3F, 19F, -3F);
      HeatRing.setTextureSize(64, 32);
      HeatRing.mirror = true;
      setRotation(HeatRing, 0F, 0F, 0F);
      Fin1 = new ModelRenderer(this, 59, 15);
      Fin1.addBox(0F, 0F, 0F, 1, 6, 1);
      Fin1.setRotationPoint(-3F, 13F, -3F);
      Fin1.setTextureSize(64, 32);
      Fin1.mirror = true;
      setRotation(Fin1, 0F, 0F, 0F);
      Fin2 = new ModelRenderer(this, 59, 15);
      Fin2.addBox(0F, 0F, 0F, 1, 6, 1);
      Fin2.setRotationPoint(-1.5F, 13F, -3F);
      Fin2.setTextureSize(64, 32);
      Fin2.mirror = true;
      setRotation(Fin2, 0F, 0F, 0F);
      Fin3 = new ModelRenderer(this, 59, 15);
      Fin3.addBox(0F, 0F, 0F, 1, 6, 1);
      Fin3.setRotationPoint(2F, 13F, -3F);
      Fin3.setTextureSize(64, 32);
      Fin3.mirror = true;
      setRotation(Fin3, 0F, 0F, 0F);
      Fin4 = new ModelRenderer(this, 59, 15);
      Fin4.addBox(0F, 0F, 0F, 1, 6, 1);
      Fin4.setRotationPoint(0.5F, 13F, -3F);
      Fin4.setTextureSize(64, 32);
      Fin4.mirror = true;
      setRotation(Fin4, 0F, 0F, 0F);
      Fin5 = new ModelRenderer(this, 59, 15);
      Fin5.addBox(0F, 0F, 0F, 1, 6, 1);
      Fin5.setRotationPoint(2F, 13F, 2F);
      Fin5.setTextureSize(64, 32);
      Fin5.mirror = true;
      setRotation(Fin5, 0F, 0F, 0F);
      Fin6 = new ModelRenderer(this, 59, 15);
      Fin6.addBox(0F, 0F, 0F, 1, 6, 1);
      Fin6.setRotationPoint(0.5F, 13F, 2F);
      Fin6.setTextureSize(64, 32);
      Fin6.mirror = true;
      setRotation(Fin6, 0F, 0F, 0F);
      Fin7 = new ModelRenderer(this, 59, 15);
      Fin7.addBox(0F, 0F, 0F, 1, 6, 1);
      Fin7.setRotationPoint(-1.5F, 13F, 2F);
      Fin7.setTextureSize(64, 32);
      Fin7.mirror = true;
      setRotation(Fin7, 0F, 0F, 0F);
      Fin9 = new ModelRenderer(this, 59, 15);
      Fin9.addBox(0F, 0F, 0F, 1, 6, 1);
      Fin9.setRotationPoint(2F, 13F, 0.5F);
      Fin9.setTextureSize(64, 32);
      Fin9.mirror = true;
      setRotation(Fin9, 0F, 0F, 0F);
      Fin8 = new ModelRenderer(this, 59, 15);
      Fin8.addBox(0F, 0F, 0F, 1, 6, 1);
      Fin8.setRotationPoint(-3F, 13F, 2F);
      Fin8.setTextureSize(64, 32);
      Fin8.mirror = true;
      setRotation(Fin8, 0F, 0F, 0F);
      Fin10 = new ModelRenderer(this, 59, 15);
      Fin10.addBox(0F, 0F, 0F, 1, 6, 1);
      Fin10.setRotationPoint(2F, 13F, -1.5F);
      Fin10.setTextureSize(64, 32);
      Fin10.mirror = true;
      setRotation(Fin10, 0F, 0F, 0F);
      Fin11 = new ModelRenderer(this, 59, 15);
      Fin11.addBox(0F, 0F, 0F, 1, 6, 1);
      Fin11.setRotationPoint(-3F, 13F, 0.5F);
      Fin11.setTextureSize(64, 32);
      Fin11.mirror = true;
      setRotation(Fin11, 0F, 0F, 0F);
      Fin12 = new ModelRenderer(this, 59, 15);
      Fin12.addBox(0F, 0F, 0F, 1, 6, 1);
      Fin12.setRotationPoint(-3F, 13F, -1.5F);
      Fin12.setTextureSize(64, 32);
      Fin12.mirror = true;
      setRotation(Fin12, 0F, 0F, 0F);
      ControlBox = new ModelRenderer(this, 0, 19);
      ControlBox.addBox(0F, 0F, 0F, 8, 10, 2);
      ControlBox.setRotationPoint(-4F, 13F, 5F);
      ControlBox.setTextureSize(64, 32);
      ControlBox.mirror = true;
      setRotation(ControlBox, 0F, 0F, 0F);
      Socket = new ModelRenderer(this, 21, 22);
      Socket.addBox(0F, 0F, 0F, 6, 6, 1);
      Socket.setRotationPoint(-3F, 13F, 7F);
      Socket.setTextureSize(64, 32);
      Socket.mirror = true;
      setRotation(Socket, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Frame1.render(f5);
    Frame2.render(f5);
    Frame3.render(f5);
    Frame4.render(f5);
    Frame5.render(f5);
    Frame6.render(f5);
    Frame8.render(f5);
    Frame9.render(f5);
    Frame10.render(f5);
    Frame11.render(f5);
    Frame12.render(f5);
    Frame13.render(f5);
    Frame14.render(f5);
    Frame15.render(f5);
    GPHS.render(f5);
    HeatSpreader.render(f5);
    TEGHolder.render(f5);
    Base.render(f5);
    HeatRing.render(f5);
    Fin1.render(f5);
    Fin2.render(f5);
    Fin3.render(f5);
    Fin4.render(f5);
    Fin5.render(f5);
    Fin6.render(f5);
    Fin7.render(f5);
    Fin9.render(f5);
    Fin8.render(f5);
    Fin10.render(f5);
    Fin11.render(f5);
    Fin12.render(f5);
    ControlBox.render(f5);
    Socket.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}